# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#BASE SETUP
title: Victoria Dominguez
description: >- # this means to ignore newlines until "baseurl:"
url: "https://victoria-dominguez.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  peeksake
google_analytics:
paginate: 5
paginate_path: "/blog/page:num/"

sass:
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate

links:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
